"""Shared WTS workflow limits used by builders and decision validation."""

MAX_SEARCH_ITERATION = 3
PRIMARY_DETAIL_BUDGET = 5
SECONDARY_DETAIL_BUDGET = 3
MAX_CARDS_PER_PATH = 30
MAX_EXPANSIONS_PER_ITERATION = 3
MAX_CANDIDATE_SCORES = MAX_SEARCH_ITERATION * (
    PRIMARY_DETAIL_BUDGET
    + SECONDARY_DETAIL_BUDGET
    + MAX_EXPANSIONS_PER_ITERATION * MAX_CARDS_PER_PATH
)
